Fundtasia/Controllers/ACreateController.cs
using Fundtasia.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Fundtasia.Controllers
{
    public class ACreateController : Controller
    {
        DBEntities1 db = new DBEntities1();

        //This controller is used to handle the Create request from View to Model

        [Authorize(Roles = "Admin, Staff")]
        public ActionResult CreateStaff()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Staff")]
        [HttpPost]
        public ActionResult CreateStaff(CreateUserVM model)
        {
            if (ModelState.IsValid)
            {
                // Check email exist
                if (IsEmailExist(model.Email))
                {
                    ModelState.AddModelError("EmailExist", "Email Already Exist");
                    return View(model);
                }

                var newStaff = new User
                {
                    Id = Guid.NewGuid(),
                    Email = model.Email,
                    Role = model.Role,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    PasswordHash = Crypto.Hash(model.PasswordHash),
                    IsEmailVerified = model.IsEmailVerified,
                    ActivationCode = Guid.NewGuid(),
                    Status = "Active"
                };

                using (DBEntities1 da = new DBEntities1())
                {
                    da.Users.Add(newStaff);
                    da.SaveChanges();

                    if (!newStaff.IsEmailVerified)
                    {
                        SendVerificaionLinkEmail(newStaff.Email, newStaff.ActivationCode.ToString());
                    }
                }
                TempData["Info"] = "Staff added.";
                return RedirectToAction("Staff", "AList");
            }

            return View(model);
        }

        [Authorize(Roles = "Admin, Staff")]
        public ActionResult CreateClientUser()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Staff")]
        [HttpPost]
        public ActionResult CreateClientUser(CreateClientUserVM model)
        {
            if (ModelState.IsValid)
            {
                // Check email exist
                var isExist = IsEmailExist(model.Email);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "Email Already Exist");
                    return View(model);
                }

                var newClientUser = new User
                {
                    // Password Hash
                    PasswordHash = Crypto.Hash(model.PasswordHash),

                    // Activation Code
                    ActivationCode = Guid.NewGuid(),

                    // Bind Data
                    Id = Guid.NewGuid(),
                    Role = "User",
                    Status = "Active",
                    LastName = model.LastName,
                    FirstName = model.FirstName,
                    Email = model.Email,
                    IsEmailVerified = model.IsEmailVerified
                };

                using (DBEntities1 dc = new DBEntities1())
                {
                    dc.Users.Add(newClientUser);
                    dc.SaveChanges();

                    if (!newClientUser.IsEmailVerified)
                    {
                        SendVerificaionLinkEmail(newClientUser.Email, newClientUser.ActivationCode.ToString());
                    }
                }
                TempData["Info"] = "Client User added.";
                return RedirectToAction("ClientUser", "AList");
            }

            return View(model);
        }

        //Create Event Action
        [Authorize(Roles = "Admin, Staff")]
        [HttpGet]
        public ActionResult CreateEvent()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Staff")]
        [HttpPost]
        public ActionResult CreateEvent(EventInsertVM model)
        {
            string err = ValidatePhoto(model.CoverImage);

            if (err != null)
            {
                ModelState.AddModelError("CoverImage", err);
            }
            
            User loginUser = (User)Session["UserSession"];

            if (ModelState.IsValid)
            {
                //Generate Id
                int m = (db.Events.Count()) + 1;
                string id = $"E{m}";

                int endIndex = model.YouTubeLink.Length;
                int startIndex = endIndex - 11;
                model.YouTubeLink = model.YouTubeLink.Substring(startIndex);

                var e = new Event
                {
                    Id = id,
                    UserId = loginUser.Id,
                    Title = model.Title,
                    View = 0,
                    CoverImage = SaveEventPhoto(model.CoverImage),
                    Target = model.Target,
                    YouTubeLink = model.YouTubeLink,
                    CreatedDate = DateTime.Now,
                    Article = model.Article
                };

                db.Events.Add(e);
                db.SaveChanges();
                TempData["Info"] = "Event added.";
                return RedirectToAction("Event", "AList");
            }
            return View(model);
        }

        [Authorize(Roles = "Admin, Staff")]
        public ActionResult CreateMerchandise()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Staff")]
        [HttpPost]
        public ActionResult CreateMerchandise(MerchandiseInsertVM model)
        {
            string err = ValidatePhoto(model.ImageURL);

            if (err != null)
            {
                ModelState.AddModelError("Image", err);
            }

            if (ModelState.IsValid)
            {
                string max = db.Merchandises.Max(m => m.Id) ?? "M000";
                int n = int.Parse(max.Substring(1));
                model.Id = (n + 1).ToString("'M'000");

                var merchandise = new Merchandise
                {
                    Id = model.Id,
                    Name = model.Name,
                    Image = SaveMerchandisePhoto(model.ImageURL),
                    Price = model.Price,
                    Status = model.Status
                };

                db.Merchandises.Add(merchandise);
                db.SaveChanges();
                TempData["Info"] = "Merchandise added.";

                return RedirectToAction("Merchandise", "AList");
            }

            return View(model);
        }

        [NonAction]
        private string ValidatePhoto(HttpPostedFileBase f)
        {
            var reType = new Regex(@"^image\/(jpeg|png)$", RegexOptions.IgnoreCase);
            var reName = new Regex(@"^.+\.(jpg|jpeg|png)$", RegexOptions.IgnoreCase);

            if (f == null)
            {
                return "No image inserted";
            }
            else if (!reType.IsMatch(f.ContentType) || !reName.IsMatch(f.FileName))
            {
                return "Only JPG or PNG image is allowed";
            }
            else if (f.ContentLength > 1 * 1024 * 1024)
            {
                // nmb = n * 1024 * 1024
                return "Image size exceeded 1Mb";
            }
            return null;
        }

        [NonAction]
        private string SaveEventPhoto(HttpPostedFileBase f)
        {
            //Generate Unique Id
            //Save the image in the format of .jpg
            string name = Guid.NewGuid().ToString("n") + ".jpg";
            string path = Server.MapPath($"~/Images/Uploads/Event/{name}");

            //Image resizing
            var img = new WebImage(f.InputStream);

            img.Resize(513, 316).Crop(1, 1).Save(path, "jpeg");

            return name;
        }

        [NonAction]
        private string SaveMerchandisePhoto(HttpPostedFileBase f)
        {
            //Generate Unique Id
            //Save the image in the format of .jpg
            string name = Guid.NewGuid().ToString("n") + ".jpg";
            string path = Server.MapPath($"~/Images/Uploads/Merchandise/{name}");

            //Image resizing
            var img = new WebImage(f.InputStream);

            img.Resize(296, 295).Crop(1, 1).Save(path, "jpeg");

            return name;
        }

        [NonAction]
        public bool IsEmailExist(string email)
        {
            //Bring DB to find the existing email
            using (db)
            {
                //FirstOrDefault() only return one record
                var v = db.Users.Where(s => s.Email == email).FirstOrDefault();
                return v != null;
            }
        }

        [NonAction]
        public void SendVerificaionLinkEmail(string email, string activationCode)
        {
            //URL to activate code
            var verifyURL = "/UserAuth/VerifyAccount/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyURL);

            //Sender and receiver
            var fromEmail = new MailAddress("fundtasia1101@gmail.com", "Fundtasia Admin");
            var toEmail = new MailAddress(email);
            var fromEmailPassword = "lkwefecbllzpgmea"; // Replace with actual password (This password only can be use in Windows computer)
            string subject = "Fundtasia(Successfull to create an account)";

            string body = "<br><br>" +
                "<p>We are glad to tell you that your Fundtasia account is successfully created. Please click on the below link to verify your account</p>" +
                "<br><br>" +
                "<a href='" + link + "'>" + link + "</a>";

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",

Fundtasia/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
@{ 
    var ao = new AjaxOptions
    {
        UpdateTargetId = "target",
        LoadingElementId = "loader",
        OnSuccess = "highlight"
    };
}

<html dir="ltr" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewBag.Title</title>

    <link rel="icon" href="~/Images/Logos/logo-icon.png">

    <!-- CSS -->
    <link href="~/Content/style-admin.css" rel="stylesheet" />
    <link href="~/Content/style.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/flashmsg.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <!-- This css code is a type of kit that need user to register the font awesome account to get it -->
    <script src="https://kit.fontawesome.com/d57fff88a0.js" crossorigin="anonymous"></script>

    <!-- Embeded CSS-->
    @RenderSection("head", false)
</head>
<body>

    <!-- Loading Circle -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>

    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

        <!-- Top Bar -->
        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin6">
                    <!-- Dashboard link-->
                    <a class="navbar-brand" href="@Url.Action("Dashboard", "Admin")">
                        <!-- Logo icon -->
                        <b class="logo-icon">
                            <img src="~/Images/Logos/small-logo-icon.png" alt="homepage" class="img-fluid" />
                        </b>
                        <!-- Logo text -->
                        <span class="logo-text">
                            <img src="~/Images/Logos/small-text-black.png" alt="homepage" class="img-fluid" />
                        </span>
                    </a>
                    <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none" href="javascript:void(0)"><i class="fas fa-bars"></i></a>
                </div>


                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <!-- This menu button will be display if width <= 766px -->
                    <ul class="navbar-nav d-none d-md-block d-lg-none">
                        <li class="nav-item text-white">
                            Text display here
                            <a class="nav-toggler nav-link waves-effect waves-light text-white" href="javascript:void(0)"><i class="fas fa-bars fa-times"></i></a>
                        </li>
                    </ul>
                    <!-- This bar will be hidden if width > 766px -->
                    <ul class="navbar-nav d-lg-block">
                        <li class="nav-item text-white ms-3">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item text-white">
                                        @Html.ActionLink("Admin", "Dashboard", "Admin")
                                    </li>
                                    <li class="breadcrumb-item">
                                        <a href="#">@ViewBag.Title</a>
                                    </li>
                                    @RenderSection("breadcrumb", false)
                                </ol>
                            </nav>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto d-flex align-items-center">
                        <!-- Search bar -->
                        @* Only display this for AList controller *@
                        @RenderSection("searchBar", false)
                        @if (ViewContext.RouteData.Values["controller"].ToString() == "AList")
                        {
                            <li>
                                @using (Ajax.BeginForm(null, null, ao, new { @class = "app-search d-none d-md-block me-3", role = "search" }))
                                {
                                    @Html.TextBox("keyword", null, new { autofocus = "", type = "search", placeholder = $"Search by {ViewBag.SearchPlaceholder}", @class = "form-control mt-0" })
                                    <a href="#" class="active">
                                        <i class="fa fa-search"></i>
                                    </a>
                                }
                            </li>
                        }
                        <!-- View Profile -->
                        <li>

                            <a class="profile-pic" href="@Url.Action("ViewProfile", "Admin")">
                                <span class="text-white font-medium">Profile</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left Side -->
        <aside class="left-sidebar" data-sidebarbg="skin6">
            <div class="scroll-sidebar">
                <nav class="sidebar-nav">
                    <!-- Sidebar link display here -->
                    <ul id="sidebarnav">
                        <li class="sidebar-item pt-2 selected">
                            <a href="@Url.Action("Dashboard", "Admin")" class="sidebar-link">
                                <i class="fas fa-chart-line"></i>
                                <span class="hide-menu">Dashbaord</span>
                            </a>
                        </li>
                        <li class="sidebar-item pt-2 selected">
                            <a href="@Url.Action("ViewProfile", "Admin")" class="sidebar-link">
                                <i class="fas fa-user"></i>
                                <span class="hide-menu">Profile</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="@Url.Action("Staff", "AList")" class="sidebar-link">
                                <i class="far fa-id-card"></i>
                                <span class="hide-menu">Staff</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="@Url.Action("ClientUser", "AList")" class="sidebar-link">
                                <i class="fas fa-users"></i>
                                <span class="hide-menu">User</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="@Url.Action("Event", "AList")" class="sidebar-link">
                                <i class="fas fa-calendar-week"></i>
                                <span class="hide-menu">Event</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="@Url.Action("Merchandise", "AList")" class="sidebar-link">
                                <i class="fas fa-store-alt"></i>
                                <span class="hide-menu">Merchandise</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="@Url.Action("Donation", "AList")" class="sidebar-link">
                                <i class="fas fa-hand-holding-usd"></i>
                                <span class="hide-menu">Donation</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="@Url.Action("MerchandiseSales", "AList")" class="sidebar-link">
                                <i class="fas fa-tshirt"></i>
                                <span class="hide-menu">Merchandise Sales</span>
                            </a>
                        </li>
                        <li class="text-center p-20">
                            <button type="button" class="btn d-grid btn-danger text-white w-100" data-bs-toggle="modal" data-bs-target="#logOutModal">Log Out</button>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>

        <!-- Right Side -->
        <div class="page-wrapper" style="min-height: 250px;">
            <div class="page-breadcrumb bg-white">
                <div class="row align-items-center">
                    <!-- Page title display here -->
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">@ViewBag.Title</h4>
                    </div>

                    <!-- Create button -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <div class="d-md-flex">
                            <ol class="breadcrumb ms-auto">
                                <li>@Html.ActionLink("Back To Client Page", "Index", "Home", null, new { @class = "text-info" })</li>
                            </ol>
                            @* Only display this for AList controller (Except Donation, because we dun create record for donation) *@
                            @if (ViewContext.RouteData.Values["controller"].ToString() == "AList" && ViewContext.RouteData.Values["action"].ToString() != "Donation")
                            {
                                @Html.ActionLink("Create", "Create" + ViewContext.RouteData.Values["action"].ToString(), "ACreate", null, new { @class = "btn btn-info  d-none d-md-block pull-right ms-3 hidden-xs hidden-sm waves-effect waves-light text-white" })
                            }
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main Content Display Here -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="white-box" id="target">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>

            <!-- Flash Message -->
            <div class="flashmsg">@TempData["Info"]</div>

            <!-- Footer display here -->
            <footer class="footer text-center">
                @DateTime.Today.Year &copy; Copyrighted by <strong>@Html.ActionLink("Fundtasia", "Index", "Home", null, new { @class = "text-dark" })</strong>
            </footer>
        </div>
    </div>

    <!-- Logout Modal Display -->
    <div id="logOutModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="logOutModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="logOutModalLabel">Log Out</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Click "Log Out" to log out your account, else click anywhere to cancel
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn d-grid btn-danger text-white" data-bs-dismiss="modal">
                        Close
                    </button>
                    @using (Html.BeginForm("Logout", "UserAuth", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        <button script="javascript:document.getElementById('logoutForm').submit()" class="btn waves-effect waves-light btn-rounded btn-light-danger text-danger">Log Out</button>
                    }
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <!-- Scripts -->
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/app-style-switcher.js"></script>
    <script src="~/Scripts/waves.js"></script>
    <script src="~/Scripts/sidebarmenu.js"></script>
    <script src="~/Scripts/custom.js"></script>
    <script src="~/Scripts/app.js"></script>

    <!-- Embeded JS -->
    @RenderSection("foot", false)
    @RenderSection("Scripts", false)
</body>
</html>