Fundtasia/Models/Donation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundtasia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime TimeDonated { get; set; }
        public decimal Amount { get; set; }
        public string EventId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}

Fundtasia/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Net.Mail;
using System.Net;
using System.Web.Security;
using Fundtasia.Models;
using System.Net.Sockets;
using System.Dynamic;
using System.Data.Entity.Validation;

namespace Fundtasia.Controllers
{
    public class HomeController : Controller
    {
        //This controller is to handle the request from the webpage that need certain information
        DBEntities1 db = new DBEntities1();

        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Donation()
        {
            var model = db.Merchandises;

            return View(model);
        }

        [Authorize]
        public ActionResult DonationPayment()
        {
            //Retrieve the event list order by to the least amount donation of the event
            //SELECT e.Id, e.Title, SUM(d.Amount)
            //FROM Event e JOIN Donation d ON e.Id = d.EventId
            //GROUP BY e.Id
            //ORDER BY SUM(d.Amount)
            ViewBag.EventList = new SelectList(db.Events.OrderBy(e => e.Donations.Count()), "Id", "Title");
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult DonationPayment(Donation model)
        {
            if (ModelState.IsValid)
            {
                User loginUser = (User)Session["UserSession"];

                var d = new Donation
                {
                    Id = Guid.NewGuid(),
                    UserId = loginUser.Id,
                    TimeDonated = DateTime.Now,
                    Amount = model.Amount,
                    EventId = model.EventId
                };

                db.Donations.Add(d);
                db.SaveChanges();
                return RedirectToAction("DonationReceipt", "Home", new { Id = d.Id });
            }

            ViewBag.EventList = new SelectList(db.Donations, "Id", "Title");
            return View(model);
        }

        [Authorize]
        public ActionResult DonationReceipt(Guid Id)
        {
            var model = db.Donations.Find(Id);
            return View(model);
        }

        [Authorize]
        public ActionResult MerchandisePayment(string Id)
        {
            if (Id == null)
            {
                return RedirectToAction("Donation", "Home");
            }

            ViewBag.EventList = new SelectList(db.Events, "Id", "Title");
            ViewBag.merchandise = db.Merchandises.Find(Id);
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult MerchandisePayment(MerchPaymentVM model)
        {
            if (ModelState.IsValid)
            {
                var merchandise = db.Merchandises.Find(model.MerchandiseId);
                User loginUser = (User)Session["UserSession"];
                var um = new UserMerchandise
                {
                    Id = Guid.NewGuid(),
                    UserId = loginUser.Id,
                    MerchandiseId = merchandise.Id,
                    Price = merchandise.Price,
                    PurchaseTime = DateTime.Now,
                    Size = model.Size,
                    FullName = model.FullName,
                    StreetAddress = model.StreetAddress,
                    State = model.State,
                    City = model.City,
                    PostalCode = model.PostalCode
                };

                db.UserMerchandises.Add(um);
                db.SaveChanges();

                return RedirectToAction("MerchandiseReceipt", "Home", new { Id = um.Id });
            }

            return View(model);
        }

        [Authorize]
        public ActionResult MerchandiseReceipt(Guid Id)
        {
            var model = db.UserMerchandises.Find(Id);
            Dictionary<string, string> state = State();
            model.State = state[model.State];
            return View(model);
        }

        public ActionResult Event(string sort = "CreatedDate", string sortdir = "DESC", int page = 1)
        {
            Func<Event, object> fn = s => s.Id;

            switch (sort)
            {
                case "CreatedDate": fn = s => s.CreatedDate; break;
                case "Title": fn = s => s.Title; break;
                case "View": fn = s => s.View; break;
            }

            var sorted = sortdir == "DESC" ? db.Events.OrderByDescending(fn) : db.Events.OrderBy(fn);

            if (page < 1)
            {
                return RedirectToAction(null, new { page = 1 });
            }

            var model = sorted.ToPagedList(page, 10);

            if (page > model.PageCount)
            {
                return RedirectToAction(null, new { page = model.PageCount });
            }

            return View(model);
        }

        public ActionResult EventDetail(string id)
        {
            if (id == null)
            {
                return RedirectToAction("Event", "Home");
            }
            var model = db.Events.Find(id);
            model.View = model.View + 1;
            db.SaveChanges();

            var donation = db.Donations.Where(s => s.EventId.Contains(id));

            if (db.Donations.FirstOrDefault(s => s.EventId.Contains(id)) != null)
            {
                ViewBag.TotalDonation = donation.Select(s => s.Amount).Sum();
                ViewBag.TotalDonor = donation.Select(s => s.UserId).Distinct().Count();
            }

            return View(model);
        }

        public Dictionary<string, string> State()
        {
            Dictionary<string, string> state = new Dictionary<string, string>(){
                {"JH", "Johor"},
                {"KD", "Kedah"},
                {"KT", "Kelantan"},
                {"MK", "Malacca"},
                {"NS", "Negeri Sembilan"},
                {"PH", "Pahang"},
                {"PN", "Penang"},
                {"PR", "Perak"},
                {"PL", "Perlis"},
                {"SB", "Sabah"},
                {"SW", "Sarawak"},
                {"SG", "Selangor"},
                {"TR", "Terengganu"}
            };
            return state;
        }
    }
}

Fundtasia/Controllers/UserAuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Net.Mail;
using System.Net;
using Fundtasia.Models;
using System.Net.Sockets;
using System.Data.Entity.Validation;
using System.Security.Claims;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Fundtasia.Controllers
{
    public class UserAuthController : Controller
    {
        //This controller is used to handle the user authentication
        DBEntities1 db = new DBEntities1();

        //Sign Up Action
        [HttpGet]
        public ActionResult SignUp()
        {
            if (User.Identity.IsAuthenticated)
            {
                //The user cannot come to signup page after login
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        //Sign Up Post Action
        [HttpPost]
        public ActionResult SignUp(SignUpVM model)
        {
            if (User.Identity.IsAuthenticated)
            {
                //The user cannot come to signup page after login
                return RedirectToAction("Index", "Home");
            }

            CaptchaResponse response = ValidateCaptcha(Request["g-recaptcha-response"]);

            bool Status = false;
            string message = "";

            //Model Validation
            if (response.Success && ModelState.IsValid)
            {
                #region Check confirm password == password
                if (model.PasswordHash != model.ConfirmPassword)
                {
                    ModelState.AddModelError("ConfirmPassword", "Confirm Password and Password does not match");
                    return View(model);
                }
                #endregion

                #region Email is already exist
                if (IsEmailExist(model.Email))
                {
                    ModelState.AddModelError("EmailExist", "Email Already Exist");
                    return View(model);
                }
                #endregion

                #region Save to DB
                var user = new User
                {
                    Id = Guid.NewGuid(),
                    Email = model.Email,
                    Role = "User",
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    PasswordHash = Crypto.Hash(model.PasswordHash),
                    IsEmailVerified = false,
                    ActivationCode = Guid.NewGuid(),
                    Status = "Active"
                };
                using (DBEntities1 da = new DBEntities1())
                {
                    da.Users.Add(user);
                    da.SaveChanges();

                    //Send email to user
                    SendVerificaionLinkEmail(user.Email, user.ActivationCode.ToString());
                    message = "You have complete to register an account in Fundtasia. The activation link has been sent to your email: " + user.Email;
                    Status = true;
                }
                #endregion
            }
            else if(!response.Success)
            {
                ModelState.AddModelError("Error", "Please complete the reCAPTCHA.");
                return View(model);
            }
            else
            {
                message = "Invalid Request";
            }

            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View(model);
        }

        public static CaptchaResponse ValidateCaptcha(string response)
        {
            string secret = System.Web.Configuration.WebConfigurationManager.AppSettings["recaptchaPrivateKey"];
            var client = new WebClient();
            var jsonResult = client.DownloadString(string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}", secret, response));
            return JsonConvert.DeserializeObject<CaptchaResponse>(jsonResult.ToString());
        }

        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            bool Status = false;
            using (db)
            {
                db.Configuration.ValidateOnSaveEnabled = false;

                var v = db.Users.Where(s => s.ActivationCode == new Guid(id)).FirstOrDefault();
                if (v != null)
                {
                    v.IsEmailVerified = true;
                    db.SaveChanges();
                    Status = true;
                }
                else
                {
                    ViewBag.Message = "Invalid Request";
                }
            }
            ViewBag.Status = Status;
            return View();
        }

        //Login Action
        [HttpGet]
        public ActionResult LogIn()
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        //Login Post Action
        [HttpPost]
        public ActionResult LogIn(UserLogin login, string ReturnUrl = "")
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Where(s => s.Email == login.Email).FirstOrDefault();

                if (user != null && VerifyPassword(user.PasswordHash, login.PasswordHash))
                {
                    if (String.Equals(user.Status, "Active"))
                    {
                        if (user.IsEmailVerified == true)
                        {
                            user.LastLoginTime = DateTime.Now;
                            user.LastLoginIP = GetLocalIPAddress();
                            db.SaveChanges();
                            SignIn(user.Id.ToString(), user.Role, login.RememberMe);
                            Session["UserSession"] = new User(user.Id, user.Email, user.Role, user.FirstName, user.LastName, user.Status, (DateTime)user.LastLoginTime, user.LastLoginIP);

                            if (ReturnUrl == "")
                            {
                                return RedirectToAction("Index", "Home");
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("Error", "Please verify your account in email");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Error", "This account has been deactivated");
                    }
                }
                else
                {
                    ModelState.AddModelError("Error", "Email and password not matched");
                }
            }
            return View(login);
        }

        public ActionResult ForgotPassword()
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(ForgotPasswordVM fgtPwdVM)
        {
            Guid resetCode = Guid.NewGuid();
            var verifyUrl = "/UserAuth/ResetPassword/" + resetCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            bool Status = false;
            string message = "";

            if (ModelState.IsValid)
            {
                if (IsEmailExist(fgtPwdVM.Email))
                {
                    using (DBEntities1 da = new DBEntities1())
                    {
                        var model = da.Users.Where(s => s.Email == fgtPwdVM.Email).FirstOrDefault();

                        // Add the verification time
                        var endTime = DateTime.Now.AddMinutes(10);

                        var fgtPwd = new PasswordReset
                        {
                            Id = resetCode,
                            UserId = model.Id,
                            TimeOver = endTime
                        };

                        da.PasswordResets.Add(fgtPwd);
                        da.SaveChanges();

                        var subject = "Password Reset Request";
                        var body = "Hi " + model.FirstName + ", <br/> You recently requested to reset your password for your account. Click the link below to reset it. " +
                             " <br/><br/><a href='" + link + "'>" + link + "</a> <br/><br/>" +
                             "If you did not request a password reset, please ignore this email or reply to let us know.<br/><br/> Thank you" +
                             "<br/><br/>Ps. this link will be disabled after " + endTime;

                        SendEmail(model.Email, body, subject);

                        message = "The reset password link has sent to your email: " + model.Email;
                        Status = true;
                    }
                }
                else
                {
                    ModelState.AddModelError("ErrorMessage", "User doesn't exists.");
                    return View();
                }
            }

            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View();
        }

        [Authorize(Roles = "User")]
        public ActionResult ViewProfile()
        {
            User userSession = (User)Session["UserSession"];
            User loginUser = db.Users.Find(userSession.Id);

            if (loginUser == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var model = new UserProfileVM
            {
                LastName = loginUser.LastName,
                FirstName = loginUser.FirstName,
                Email = loginUser.Email
            };

Fundtasia/Views/Home/Donation.cshtml
@model IEnumerable<Merchandise>
@{
    ViewBag.Title = "Donation";
}

@section head{
    <link href="~/Content/donation.css" rel="stylesheet" />
}

<div class="row">
    <div class="col-lg-8 mx-auto">
        <h2 class="section-title text-center wow fadeInDown" data-wow-duration="2s" data-wow-delay="400ms">
            <b>WHY DONATE TO US?</b>
        </h2>
        <p class="wow fadeInDown" data-wow-duration="2.5s" data-wow-delay="600ms">
            Your donation creates hope and opportunity within our community by empowering us to minister to people’s physical, social and spiritual needs.
            When a child is born into an impoverished family, they enter the first phase of a long and challenging cycle that can run for generations. When a
            family lives in poverty, they usually have very limited or no access to resources. But you are able to change that by contributing!
        </p>
    </div>
</div>

<img src="~/Images/Background/poverty-eradication.jpg" class="mt-5 d-block mx-auto wow fadeInDown" style="width:70%;" data-wow-duration="2s" data-wow-delay="800ms"/>
<p class="wow fadeInDown" data-wow-duration="2s" data-wow-delay="800ms"><i>Image of a child facing poverty in Mumbai, India.</i></p>

<div class="row wow fadeInDown" data-wow-duration="1.5s" data-wow-delay="400ms">
    <div class="col-lg-8 mx-auto mt-5">
        <h2 class="section-title text-center" id="donate">
            <b>TAKE PART!</b>
        </h2>
        <p>
            You can help us to decrease poverty issues by donating to our charity that focuses on helping them. Funds that have been raised will 100% go towards
            the people that are struggling with poverty and we will provide them with basic needs to help them survive and ease their struggles! You are able to
            donate a minimum amount of RM1! You may also support us by buying our merchandise and the funds will also go directly to those in need.
        </p>
    </div>
</div>

<div class="wow fadeInDown" data-wow-duration="1.5s" data-wow-delay="400ms">
    <div>
        <h2 class="mt-5"><b>DONATE</b></h2>
    </div>
    <div class="card" style="width: 30rem; margin-bottom:100px">
        <div class="card-title">
            <img src="~/Images/Logos/donate icon.png" class="card-img-top">
        </div>
        <div class="card-body">
            <!-- For index page purpose -->
            <span id="merchandise"></span>
            <form action="~/Home/DonationPayment">
                <input type="submit" value="Click Here to Donate" class="donate-submit" />
            </form>
        </div>
    </div>
</div>

<div class="container">
    <div class="wow fadeInDown" data-wow-duration="1.5s" data-wow-delay="400ms">
        <h2><b>MERCHANDISE</b></h2>
        <p>*All of the funds will directly contribute to the fundraising event.</p>
    </div>

    <div class="row wow fadeInDown" data-wow-duration="1.5s" data-wow-delay="400ms">

        @foreach (var m in Model) //will display data from Admin Merchandise
        {
            if (String.Equals(m.Status, "Available"))
            {
                <div class="col-sm-6 mt-4">
                    <div class="card">
                        <img src="~/Images/Uploads/Merchandise/@m.Image" style="height:500px"/>
                        <div class="card-body">
                            <p>RM @m.Price.00</p>
                            <h4 class="card-title">@m.Name</h4>
                            <form method="get" action="~/Home/MerchandisePayment?Id=@m.Id">
                                <input type="submit" value="Purchase" id="submitBtn" class="button-normal" data-get="/Home/MerchandisePayment?Id=@m.Id" /> @*After submit, will pass this data to Payment*@
                            </form>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

Fundtasia/Views/Home/DonationPayment.cshtml
@using Fundtasia
@model DonationPaymentVM
@{
    ViewBag.Title = "Donation Payment";

    IEnumerable<Donation> donation = ViewBag.Donation;
}

<link href="~/Content/payment.css" rel="stylesheet" />

<body>
    <form method="post" action="">
        <div class="card" style="width: 28rem;">
            <div class="card-body">
                <h2 class="card-title">💰 Donation Amount 💰</h2>
                <h5 class="card-title">Enter the amount:</h5>
                @Html.TextBoxFor(d => d.Amount, new { @class = "form-control", autocomplete = "off", placeholder = "Enter here" })
                @Html.ValidationMessageFor(d => d.Amount, "", new { @class = "error-msg" })
                <br />
                <h5 class="card-title">Select Event:</h5>
                @Html.DropDownListFor(d => d.EventId, (SelectList)ViewBag.EventList, "-- Select One --", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.EventId, "", new { @class = "error-msg" })
            </div>
        </div>

        <div class="card" style="width: 28rem;">
            <div class="card-body">
                <h2 class="card-title">💳 Card Details 💳</h2>
                <h5>Name : </h5>
                @Html.TextBoxFor(d => d.Name, new { @class = "form-control", autocomplete = "off", placeholder = "Name here" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "error-msg" })
                <h5>Card Number : </h5>
                @Html.TextBoxFor(d => d.CardNumber, new { @class = "form-control", autocomplete = "off", placeholder = "Card Number here" })
                @Html.ValidationMessageFor(m => m.CardNumber, "", new { @class = "error-msg" })
                <h5>Expiry Date : </h5>
                @Html.TextBoxFor(d => d.ExpiryDate, new { @class = "form-control", autocomplete = "off", placeholder = "Expiry Date here" })
                @Html.ValidationMessageFor(m => m.ExpiryDate, "", new { @class = "error-msg" })
                <h5>CVV : </h5>
                @Html.TextBoxFor(d => d.CVV, new { @class = "form-control", autocomplete = "off", placeholder = "CVV here" })
                @Html.ValidationMessageFor(m => m.CVV, "", new { @class = "error-msg" })

                <input type="submit" value="Proceed" class="donate-submit" style="margin-top:40px;"/>
            </div>
        </div>
    </form>
</body>

@section foot
{
    <script>

    </script>
}

Fundtasia/Views/Home/DonationReceipt.cshtml
@{
    ViewBag.Title = "Donation Receipt";
}
@section head{
    <link href="~/Content/receipt.css" rel="stylesheet" />
}

<div class="card">
    <div class="card-body">
        <h2 class="card-title">🙏 <u>THANK YOU FOR DONATING!</u> 🙏</h2>
        <table class="receipt-table">
            <tr>
                <td>
                    <img src="~/Images/Uploads/Event/@Model.Event.CoverImage" style="height:300px; object-fit:cover;" />
                </td>
            </tr>
            <tr>
                <td>Name :</td>
                <td><div class="receipt-align"><b>@Model.User.LastName @Model.User.FirstName</b></div></td>
            </tr>
            <tr>
                <td>Event Name :</td>
                <td><div class="receipt-align"><b>@Model.Event.Title</b></div></td>
            </tr>
            <tr>
                <td>Time Donated :</td>
                <td><div class="receipt-align"><b>@Model.TimeDonated</b></div></td>
            </tr>
            <tr>
                <td>Amount Donated :</td>
                <td><div class="receipt-align"><b><u>RM @Model.Amount.ToString("F")</u></b></div></td>
            </tr>

        </table>
    </div>
</div>


<br />
<button class="btn button-normal" data-get="/Home/Donation">Back to Donation Page</button>
<br />
<br />

Fundtasia/Views/Home/Event.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<Event>
@{
    ViewBag.Title = "Event";
}

<div class="row wow fadeInDown" data-wow-duration="1.5s" data-wow-delay="400ms">
    <div class="col-lg-8 mx-auto">
        <h2 class="section-title text-center">
            <span>Read our</span>
            Event
        </h2>
    </div>
</div>

<div class="row">
    @foreach (var s in Model)
    {
        <div class="col-lg-6 col-md-6 wow fadeInDown" data-wow-duration="1.5s" data-wow-delay="400ms">
            <div class="post">
                <div class="post-media post-image">
                    <a href="@Url.Action("EventDetail", "Home", new { id = s.Id })"><img src="~/Images/Uploads/Event/@s.CoverImage" class="img-fluid w-100" /></a>
                </div>
                <div class="post-body">
                    <div class="post-meta">
                        <span class="post-author">BY @s.User.FirstName @s.User.LastName</span>
                        <div class="post-meta-date">
                            <span class="day">@s.CreatedDate.Day</span>
                            <span class="month">@s.CreatedDate.ToString("MMMM")</span>
                            <span class="year">@s.CreatedDate.Year</span>
                        </div>
                    </div>
                    <div class="entry-header">
                        <div class="entry-title">
                            <h2>
                                <a href="@Url.Action("EventDetail", "Home", new { id = s.Id })">@s.Title</a>
                            </h2>
                        </div>
                    </div>
                    <div class="entry-content">
                        <p>@Html.Raw(s.Article.Substring(0, s.Article.IndexOf("."))).</p>
                    </div>
                    <div class="post-footer">
                        <div class="row">
                            <div class="col">
                                <a href="@Url.Action("EventDetail", "Home", new { id = s.Id })" class="btn-link">Read More <i class="fa fa-arrow-right"></i></a>
                            </div>
                            <div class="col">
                                <i class="fas fa-eye"></i> @s.View
                            </div>
                            <!-- <div class="col">
                                <i class="fas fa-thumbs-up"></i> @* *@s.UserEvents.Where(e => e.EventId.Contains(s.Id)).Count()
                            </div> -->
                        </div>

                    </div>
                </div>
            </div>
        </div>
    }
</div>

Fundtasia/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="container">
    <div class="row">
        <div class="col-lg-4 wow fadeInLeft" data-wow-duration="1.5s" data-wow-delay="200ms">
            <div class="intro-left-content">
                <h2 class="column-title">
                    <span>Why Join Fundtasia ?</span>
                    Where the poor get help, the hurting are comforted, and the desperate find hope.
                </h2>
                <p>
                    Participate our own events to learn more ！
                    Learn about our organisation ongoing events helping for poor victims.
                </p>
                <a href="@Url.Action("SignUp", "UserAuth")" class="btn wow fadeInUp" data-wow-duration="1.5s" data-wow-delay="2000ms">Join Us</a>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="row">
                <div class="col-lg-6 wow fadeInUp" data-wow-duration="1.5s" data-wow-delay="400ms">
                    <a href="@Url.Action("Event", "Home")">
                        <div class="single-intro-text mb-30">
                            <h3 class="ts-title">Charity Events</h3>
                            <p>
                                Spread our love and kindness.
                                Our main purpose to help more people.
                                We provide community support and financial protection.
                            </p>
                            <span class="count-number">01</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6 wow fadeInUp" data-wow-duration="1.5s" data-wow-delay="800ms">
                    <a href="~/Home/Donation#donate">
                        <div class="single-intro-text mb-30">
                            <h3 class="ts-title">Donatation support</h3>
                            <p>
                                Hard to find time participate the events?
                                Support Fundtasia by money donation.
                                Or buying our merchant to support us !
                            </p>
                            <span class="count-number">02</span>

                        </div>
                    </a>
                </div>
                <div class="col-lg-6 wow fadeInUp" data-wow-duration="1.5s" data-wow-delay="1200ms">
                    <a href="~/Home/Donation#merchandise">
                        <div class="single-intro-text mb-30">
                            <h3 class="ts-title">Merchandise</h3>
                            <p>
                                Interested for our merchant in clothes?
                                Buy our merchant to support us!
                                Include various choice of design selections.
                                Shop now for more details.
                            </p>
                            <span class="count-number">03</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6 wow fadeInUp" data-wow-duration="1.5s" data-wow-delay="1600ms">
                    <div class="single-intro-text mb-30">
                        <h3 class="ts-title">Make a difference</h3>
                        <p>
                            Funtasia is a charity that journeys by provide food aid, community support,
                            distribute financial protection, and run educational programs.
                        </p>
                        <span class="count-number">04</span>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>